<a href="https://colab.research.google.com/github/YunusEmre214/Data_Science_Colab/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Veri Bilimi
import pandas as pd

In [ ]:
#1.Veri setini yükle
df=pd.read_csv("e_ticaret_veri_seti.csv")

In [ ]:
#2.Veri setinin ilk ve son satırları inncele
print(df.head())

  siparis_id musteri_id       siparis_tarihi      sehir              bolge  \
0  SIP101125    MUS1391  2024-01-13 17:06:00   İstanbul            Marmara
1  SIP100837    MUS1347  2025-03-17 21:13:00  Gaziantep  Güneydoğu Anadolu
2  SIP100050    MUS1066  2025-06-03 12:42:00    Kayseri         İç Anadolu
3  SIP100263    MUS1008  2024-08-10 15:13:00    Antalya            Akdeniz
4  SIP100707    MUS1291  2024-08-19 08:24:00  Gaziantep  Güneydoğu Anadolu

     kategori              urun_adi  adet  birim_fiyat  indirim_orani  \
0    Kozmetik          Nemlendirici     1       414.51           0.05
1        Spor           Dambıl Seti     2      1475.15           0.10
2       Kitap  İş Analitiği Rehberi     1       289.02           0.05
3       Kitap          Girişimcilik     5       194.78           0.00
4  Elektronik             Powerbank     3       841.80           0.05

   kargo_ucreti      odeme_turu musteri_tipi  teslimat_gunu  musteri_puani  \
0          49.9     Kredi Kartı         Yeni            3.0            5.0
1          29.9     Banka Kartı          VIP            4.0            1.0
2          29.9     Kredi Kartı       Mevcut            6.0            2.0
3          49.9    Kapıda Ödeme         Yeni            3.0            5.0
4          39.9  Dijital Cüzdan       Mevcut            4.0            5.0

  iade_durumu  kar_marji_orani  toplam_tutar
0       Hayır            0.220        443.68
1       Hayır            0.361       2685.17
2       Hayır            0.348        304.47
3       Hayır            0.250       1023.80
4       Hayır            0.280       2439.03

In [ ]:
print(df.tail())

     siparis_id musteri_id       siparis_tarihi      sehir              bolge  \
1423  SIP101093    MUS1187  2024-06-08 20:42:00   İstanbul            Marmara
1424  SIP101193    MUS1297  2025-11-06 08:17:00  Gaziantep  Güneydoğu Anadolu
1425  SIP101210    MUS1122  2025-03-07 09:07:00        NaN            Marmara
1426  SIP101060    MUS1189  2025-04-19 21:52:00    Kocaeli            Marmara
1427  SIP100642    MUS1289  2024-09-22 16:36:00     Ankara         İç Anadolu

        kategori         urun_adi  adet  birim_fiyat  indirim_orani  \
1423        Spor        Yoga Matı     1       772.23           0.00
1424        Spor            Suluk     2       187.03           0.00
1425  Elektronik           Webcam     4       894.47           0.10
1426       Kitap  Veri Bilimi 101     2       248.55           0.05
1427    Kozmetik      Güneş Kremi     1       424.84           0.20

      kargo_ucreti      odeme_turu musteri_tipi  teslimat_gunu  musteri_puani  \
1423          29.9     Kredi Kartı       Mevcut            3.0            2.0
1424          59.9     Kredi Kartı         Yeni            2.0            4.0
1425          49.9     Kredi Kartı       Mevcut            3.0            5.0
1426          59.9     banka karti         Yeni            4.0            3.0
1427           0.0  Dijital Cüzdan         Yeni            2.0            4.0

     iade_durumu  kar_marji_orani  toplam_tutar
1423       Hayır            0.275        802.13
1424        Evet            0.243        433.96
1425       Hayır            0.355       3269.99
1426       Hayır            0.373        532.14
1427       Hayır            0.317        339.87

In [ ]:
#3.Veri setinin boyutunu ve sütunlarını kontrol etmek
row,column=df.shape
print(df.shape)
print(f"Row:{row}")
print(f"Column:{column}")

(1428, 18)
Row:1428
Column:18

In [ ]:
#sütun isimleri
for i, column in enumerate(df.columns,start=1):
  print(f"{i}:{column}")

1:siparis_id
2:musteri_id
3:siparis_tarihi
4:sehir
5:bolge
6:kategori
7:urun_adi
8:adet
9:birim_fiyat
10:indirim_orani
11:kargo_ucreti
12:odeme_turu
13:musteri_tipi
14:teslimat_gunu
15:musteri_puani
16:iade_durumu
17:kar_marji_orani
18:toplam_tutar

In [ ]:
#4.Veri setinin genel bilgisini inceleme
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   siparis_id       1428 non-null   object
 1   musteri_id       1428 non-null   object
 2   siparis_tarihi   1428 non-null   object
 3   sehir            1403 non-null   object
 4   bolge            1428 non-null   object
 5   kategori         1428 non-null   object
 6   urun_adi         1428 non-null   object
 7   adet             1428 non-null   int64
 8   birim_fiyat      1428 non-null   float64
 9   indirim_orani    1412 non-null   float64
 10  kargo_ucreti     1428 non-null   float64
 11  odeme_turu       1393 non-null   object
 12  musteri_tipi     1386 non-null   object
 13  teslimat_gunu    1400 non-null   float64
 14  musteri_puani    1372 non-null   float64
 15  iade_durumu      1428 non-null   object
 16  kar_marji_orani  1428 non-null   float64
 17  toplam_tutar     1428 non-null   float64
dtypes: float64(7), int64(1), object(10)
memory usage: 200.9+ KB

In [ ]:
#5.Özet istatislikleri görüntüleme
df.describe()

,adet,birim_fiyat,indirim_orani,kargo_ucreti,teslimat_gunu,musteri_puani,kar_marji_orani,toplam_tutar
count,1428.000000,1428.000000,1412.000000,1428.000000,1400.000000,1372.000000,1428.000000,1428.000000
mean,2.136555,658.477654,0.052054,39.725140,3.370714,4.002187,0.302799,1370.590336
std,2.015770,1042.414639,0.060115,14.185017,1.825990,1.096707,0.069795,2961.689500
min,1.000000,93.110000,0.000000,0.000000,1.000000,0.000000,0.180000,89.680000
25%,1.000000,199.185000,0.000000,29.900000,2.000000,3.000000,0.244750,323.855000
50%,2.000000,287.120000,0.050000,39.900000,3.000000,4.000000,0.305000,669.135000
75%,3.000000,819.177500,0.100000,49.900000,4.000000,5.000000,0.362000,1390.950000
max,38.000000,18145.230000,0.200000,59.900000,31.000000,7.000000,0.420000,63870.200000

In [ ]:
#6.Veri tiplerini kontrol etme
df.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [ ]:
#7.Sayısal ve kategorik sütunların ayrılması
numeric_column=df.select_dtypes(include=["int64","float64"]).columns
categorical_column=df.select_dtypes(include=["object"]).columns
print(f"Numeric Column:{numeric_column}")
print(f"Categorical Column:{categorical_column}")

Numeric Column:Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')
Categorical Column:Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [ ]:
#8.Benzersiz(unique) değer sayıların incelenmesi
for column in df.columns:
  print(f"{column}:{df[column].nunique()}")

siparis_id:1400
musteri_id:422
siparis_tarihi:1398
sehir:19
bolge:6
kategori:15
urun_adi:30
adet:10
birim_fiyat:1381
indirim_orani:5
kargo_ucreti:5
odeme_turu:12
musteri_tipi:7
teslimat_gunu:11
musteri_puani:8
iade_durumu:2
kar_marji_orani:241
toplam_tutar:1397

In [ ]:
#Missing Value
#9.Eksik verileri tespit etme
missing_data=df.isnull().sum()
print(missing_data)

siparis_id          0
musteri_id          0
siparis_tarihi      0
sehir              25
bolge               0
kategori            0
urun_adi            0
adet                0
birim_fiyat         0
indirim_orani      16
kargo_ucreti        0
odeme_turu         35
musteri_tipi       42
teslimat_gunu      28
musteri_puani      56
iade_durumu         0
kar_marji_orani     0
toplam_tutar        0
dtype: int64

In [ ]:
#10.Eksik veri oranları hesaplama
missing_data_rate=(missing_data/len(df))*100
print(missing_data_rate)

siparis_id         0.000000
musteri_id         0.000000
siparis_tarihi     0.000000
sehir              1.750700
bolge              0.000000
kategori           0.000000
urun_adi           0.000000
adet               0.000000
birim_fiyat        0.000000
indirim_orani      1.120448
kargo_ucreti       0.000000
odeme_turu         2.450980
musteri_tipi       2.941176
teslimat_gunu      1.960784
musteri_puani      3.921569
iade_durumu        0.000000
kar_marji_orani    0.000000
toplam_tutar       0.000000
dtype: float64

In [ ]:
#11.Eksik veri içeren satırları incele
missing_data_row=df[df.isnull().any(axis=1)]
missing_data_row.head(10)

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar
19,SIP100677,MUS1148,2024-07-11 16:24:00,Adana,Akdeniz,Spor,Dambıl Seti,4,1517.65,0.0,29.9,Kapıda Ödeme,Mevcut,3.0,NaN,Hayır,0.311,6100.50
33,SIP101126,MUS1406,2024-09-11 20:05:00,Mersin,Akdeniz,Elektronik,Bluetooth Hoparlör,1,1159.89,0.1,39.9,Kredi Kartı,NaN,2.0,4.0,Hayır,0.204,1083.80
50,SIP101040,MUS1386,2025-04-01 09:30:00,Trabzon,Karadeniz,Spor,Dambıl Seti,1,1554.15,0.0,49.9,Banka Kartı,NaN,4.0,5.0,Hayır,0.217,1604.05
60,SIP100890,MUS1271,2024-11-07 19:47:00,İzmir,Ege,Kitap,Girişimcilik,4,216.38,NaN,49.9,Kredi Kartı,Yeni,1.0,3.0,Hayır,0.199,915.42
61,SIP101317,MUS1060,2024-09-05 20:49:00,NaN,Akdeniz,Ev ve Yaşam,Saklama Kutusu,1,233.63,0.1,29.9,Dijital Cüzdan,Yeni,5.0,2.0,Hayır,0.385,240.17
70,SIP100715,MUS1033,2024-11-10 21:50:00,İstanbul,Marmara,Ev ve Yaşam,Termos,1,552.05,0.0,39.9,NaN,Mevcut,2.0,3.0,Hayır,0.185,591.95
82,SIP100807,MUS1431,2025-01-07 14:12:00,Ankara,İç Anadolu,Kozmetik,Güneş Kremi,1,451.28,0.0,49.9,Kredi Kartı,NaN,4.0,5.0,Hayır,0.315,501.18
84,SIP100679,MUS1310,2024-05-20 18:51:00,İzmir,Ege,Ev ve Yaşam,Termos,2,477.62,0.0,49.9,Kredi Kartı,Mevcut,NaN,4.0,Hayır,0.323,1005.14
86,SIP101071,MUS1131,2024-09-18 12:24:00,NaN,İç Anadolu,Elektronik,Powerbank,1,816.74,0.0,39.9,Banka Kartı,Yeni,3.0,5.0,Hayır,0.301,856.64
92,SIP101366,MUS1347,2025-03-04 14:00:00,Bursa,Marmara,Ev ve Yaşam,Organizer,1,272.40,0.0,29.9,Kredi Kartı,Mevcut,1.0,NaN,Hayır,0.212,302.30

In [26]:
#12.Eksik verileri silme
df_deleted=df.dropna()
df_deleted.shape

(1239, 18)

In [30]:
#13.Sayısal eksik verilerin ortalama ile doldurulması
df_average=df.copy()
numeric_column=df_average.select_dtypes(include=["int64","float64"]).columns
numeric_column

Index(['adet', 'birim_fiyat', 'indirim_orani', 'kargo_ucreti', 'teslimat_gunu',
       'musteri_puani', 'kar_marji_orani', 'toplam_tutar'],
      dtype='object')

In [31]:
for column in numeric_column:
  df_average[column]=df_average[column].fillna(df_average[column].mean())
df_average[numeric_column].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [32]:
#14.Sayısal eksik verileri medyan ile doldurma
df_median=df.copy()
for column in numeric_column:
  df_median[column]=df_median[column].fillna(df_median[column].median())
df_median[numeric_column].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [33]:
#15.Sayısal eksik verileri mod ile doldurma
df_mod=df.copy()
for  column in numeric_column:
  df_mod[column]=df_mod[column].fillna(df_mod[column].mode()[0])
df_mod[numeric_column].isnull().sum()

adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
teslimat_gunu      0
musteri_puani      0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [34]:
#16.Kategorik eksik verileri mod ile doldurma
df_mod_categorical=df.copy()
categorical_column=df_mod_categorical.select_dtypes(include=["object"]).columns
categorical_column

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'odeme_turu', 'musteri_tipi', 'iade_durumu'],
      dtype='object')

In [36]:
for column in categorical_column:
  mod_value=df_mod_categorical[column].mode()[0]
  df_mod_categorical[column]=df_mod_categorical[column].fillna(mod_value)
df_mod_categorical[categorical_column].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [37]:
#17.Kategorik eksik verileri sabit bir değer ile doldurulalım
df_constant_categorical=df.copy()
for column in categorical_column:
  df_constant_categorical[column]=df_constant_categorical[column].fillna("Bilinmiyor")
df_constant_categorical[categorical_column].isnull().sum()

siparis_id        0
musteri_id        0
siparis_tarihi    0
sehir             0
bolge             0
kategori          0
urun_adi          0
odeme_turu        0
musteri_tipi      0
iade_durumu       0
dtype: int64

In [38]:
#18.Eğitimde kullanacağımız güncel veri seti
#sayısal eksik verileri medyan ile doldur
#Kategorik eksik verileri mod ile doldur
df_current=df.copy()
for column in numeric_column:
  df_current[column]=df_current[column].fillna(df_current[column].median())
for column in categorical_column:
  mod_value=df_current[column].mode()[0]
  df_current[column]=df_current[column].fillna(mod_value)

In [40]:
df_current.isnull().sum()

siparis_id         0
musteri_id         0
siparis_tarihi     0
sehir              0
bolge              0
kategori           0
urun_adi           0
adet               0
birim_fiyat        0
indirim_orani      0
kargo_ucreti       0
odeme_turu         0
musteri_tipi       0
teslimat_gunu      0
musteri_puani      0
iade_durumu        0
kar_marji_orani    0
toplam_tutar       0
dtype: int64

In [41]:
#19.Düzenlenmiş veri setini kaydedelim
record_file="e_ticaret_veri_seti_current.csv"
df_current.to_csv(record_file,index=False)